volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: kentiy2717/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/app/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: kentiy2717/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/
  gateway:
    image: kentiy2717/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media/
    ports:
      - "9000:80"
    depends_on:
      - backend
